version: '3.8'

services:
  # Development service
  dev:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - VITE_PORT=3000
    command: pnpm dev --host 0.0.0.0 --port 3000
    env_file:
      - .env

  # Production service
  prod:
    build:
      context: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    command: pnpm build && pnpm preview --host 0.0.0.0 --port 80 